name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "v*d2iq*" # Match only d2iq release tags, e.g., v1.1.3-d2iq.0

permissions:
  contents: write # Allow to create a release.

jobs:
  build:
    name: create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"
      - name: generate release artifacts
        run: |
          make release
      - name: generate release notes
        run: |
          make release-notes
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/*
          body_path: _releasenotes/${{ env.RELEASE_TAG }}.md
      - name: Build and push docker images
        run: |
          export REGISTRY=docker.io/mesosphere
          export PROD_REGISTRY=$REGISTRY
          make ALL_ARCH="amd64 arm64" docker-build-all
          make ALL_ARCH="amd64 arm64" docker-push-all
